###test server
http://localhost:60000


###
POST http://localhost:60200/api/users/signup
content-type: application/json

{
    "firstname": "Khaya",
    "lastname": "Mbatha",
    "email": "khayam@gmail.com",
    "password": "123456"
}


###

POST http://localhost:60200/api/users/signin
content-type: application/json

{
    "email":"khayam@gmail.com",
    "password": "1234567"
}