@SERVER=http://localhost:50000


### test server
GET {{SERVER}}



### REGISTER NEW USER
POST {{SERVER}}/api/users/register
content-type: application/json

{
    "firstname": "Khaya",
    "lastname": "mbatha",
    "email": "khahjuikyam55@gmail.com",
    "password": "123456"
}



### LOGIN USER
POST {{SERVER}}/api/users/login
content-type: application/json

{
    "email":"khayam@gmail.com",
    "password": "123456"
}

